### ISSUE TITLE
Uncaught Your ghci path is not valid

### ISSUE THREAD

**Issue by planeview** [seansay/atom-tidal#10]
[Enter steps to reproduce below:]

1. opening file from desktop (named test.tidal)
2. booting Tidal

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tidal](https://github.com/seansay/atom-tidal) package, v0.6.5

### Stack Trace

Uncaught Your ghci path is not valid

```
At /Users/alagg/.atom/packages/tidal/lib/repl.coffee:41

undefined
```

### Commands

```
     -3:29.8 settings-view:open (ul.list-inline.tab-bar.inset-panel)
     -0:39.7 tidal:eval (atom-text-editor.editor.is-focused)
     -0:28.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:02.0 tidal:eval (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "tidal": {}
}
```

### Installed Packages

```coffee
# User
tidal, v0.6.5

# Dev
No dev packages
```

**Comment by seansay** [comment]
hey, where is the `ghci` locate in your computer? the default is `/usr/local/bin/ghci`, you may change this if this is not where your `ghci` is.

you can change the `ghci` path in the packge setting ( I think I need to add a alert info to display something if the current `ghci` is not found)

**Comment by planeview** [comment]
Hi, thank you for the quick reply.
The ghci in the default location, and that's where Im telling it to look through tidal settings in Atom...

**Comment by seansay** [comment]
sorry that I don't get you, my english is not very well...

Do you get this working right now?

**Comment by planeview** [comment]
No...I'm still trying but it keeps saying "Uncaught Your ghci path is not valid"
and bellow that:
/Users/alagg/.atom/packages/tidal/lib/repl.coffee:41
should my file (test.tidal) be in a specific location?

**Comment by seansay** [comment]
did you run `which ghci` in your terminal? where is it

**Comment by planeview** [comment]
yes its in the default folder...

**Comment by seansay** [comment]
I don't think the file needs to be in specific location..

I just publish a patch , it should throw a erorr with current ghci path, can you update and look at where it is?

**Comment by planeview** [comment]
if I did it correctly, no luck here either...

**Comment by seansay** [comment]
did the error msg  output your ghci path?

**Comment by planeview** [comment]
![invalid ghci path](https://cloud.githubusercontent.com/assets/3070744/6665559/93848af4-cbe3-11e4-92ab-ce73b54d7e6e.png)

i attached a screenshot of the error msg i got...
thanks again
Alex

**Comment by seansay** [comment]
If the code is rightj ,this suppose to mean there isn't a file in the path `/usr/local/bin/ghci`, how do you install haskell thing? can you find ghci in if you run `ls` in `/usr/local/bin/?

**Comment by planeview** [comment]
I followed the instructions, installed it via terminal. when I run the ls command it shows in the right path...

**Comment by seansay** [comment]
@yaxu
any idea?

**Comment by planeview** [comment]
i found out the solution:
my cabal installation wont work on my os (yosemite):
https://github.com/tidalcycles/Tidal/issues/45

so I installed it from source. Additionally dirt wont find the samples unless run from terminal - but I dont know if this is the right place to talk about that.

Either way, it works now! thank you for your time!
alex
