### ISSUE TITLE
'Paragraph' eval not including punctuation

### ISSUE THREAD

**Issue by yaxu** [seansay/atom-tidal#11]
As mentioned on another issue..

I noticed that with multiline evals, some characters aren't counted, for example the trailing square bracket here isn't included, and the pattern doesn't evaluate:

```
d1 $ weave 16 (speed (scale 1 1.4 sine1)) [jux (iter 8) $ sound "sd8:4*4",
                                           jux (iter 4) $ sound "bd*2",
                                           jux (iter 3) $ sound "sd8:3*4"
                                          ]
```
It seems to be caused by the use of `\w` in regex here: 
https://github.com/atom/atom/blob/f7bb8aab9e33090cc8455cfdf045efe6257568d9/src/app/language-mode.coffee#L183
I'll raise an issue over there.

**Comment by seansay** [comment]
`
  # Right now, a paragraph is a block of text bounded by and empty line or a
  # block of text that is not the same type (comments next to source code).
`

from definition looks like atom core's bug!

**Comment by yaxu** [comment]
Ace :)
