### ISSUE TITLE
Uncaught Your ghci path: '/usr/local/bin/ghci' is invalid

### ISSUE THREAD

**Issue by koloskus** [seansay/atom-tidal#15]
I have incredibly minimal experience with installing things like this, so apologies if this is some really easy problem I missed. I installed everything as it said to on tidal.lurk.org. I had to use the JackOSX Installer if that makes any difference.

Any advice on what to do here?

[Enter steps to reproduce below:]

1. Open empty document
2. Save As "test.tidal"
3. Attempt to boot Tidal from Packages menu

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10
**Thrown From**: [tidal](https://github.com/seansay/atom-tidal) package, v0.6.6

### Stack Trace

Uncaught Your ghci path: '/usr/local/bin/ghci' is invalid

```
At /Users/Zavras/.atom/packages/tidal/lib/repl.coffee:41

undefined
```

### Commands

```
     -0:00.3.0 tidal:boot (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
tidal, v0.6.6

# Dev
No dev packages
```

**Comment by yaxu** [comment]
Hi, I think you need to open the preferences/settings in Atom, click on 'packages', find the tidal package and click on 'settings', then set the "Ghci path" setting to `/usr/bin/ghci`

If that doesn't work, open a terminal and type `which ghci`, this should give you the correct ghci path to use.

**Comment by koloskus** [comment]
It was set to the default, I'm not sure what was going on. I ended up just reinstalling everything from the start and that seemed to fix it. Thanks for the response!

**Comment by johannesgunnar** [comment]
Just wanted to add that I ran into the same problem. it was set to "default: /usr/bin/ghci" after installation. I deleted it and put in "/usr/bin/ghci" and after that everything worked. (I am running Ubuntu 14.04)

**Comment by berglar** [comment]
hey @johannesgunnar ! 
I think you meant that you updated the path from
`
default: /usr/local/bin/ghci
`
and that you updated it to
`
default: /usr/bin/ghci
`
Thanks for posting! This was the trick for me as well :)

**Comment by faulda** [comment]
Also worked for me. Thanks for the fix.

**Comment by Liamhbray** [comment]
Hi I have the same error, i have tried the above fix, but was not able to resolve the problem. Any help would be great. 



**Atom Version**: 1.7.3
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [tidal](https://github.com/seansay/atom-tidal) package, v2.1.0


### Stack Trace

Uncaught Your ghci path: '/usr/bin/ghci' is invalid

```
At /C:/Users/Liam%20Bray/.atom/packages/tidal/lib/repl.coffee:94

undefined
```

### Commands

```
     -4:31.3.0 application:new-file (atom-text-editor.editor.is-focused)
     -4:19 core:save (ul.list-inline.tab-bar.inset-panel)
     -3:49.5.0 tidal:boot (ul.list-inline.tab-bar.inset-panel)
     -0:45.1.0 core:paste (atom-text-editor#tidal.ghciPath.editor.mini.is-focused)
     -0:12.2.0 tidal:boot (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "tidal": {
    "ghciPath": "/usr/bin/ghci"
  }
}
```

### Installed Packages

```coffee
# User
tidal, v2.1.0

# Dev
No dev packages
```
