### ISSUE TITLE
Workspace.getActiveEditor is deprecated.

### ISSUE THREAD

**Issue by robjac** [seansay/atom-tidal#17]
Hey Sean, any interest in trying to clean up atom-tidal so that we don't get deprecated calls? 

Just a thought!

-Robbie Jacobs

Call ::getActiveTextEditor instead
```
Workspace.getActiveEditor (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:1022:12)
REPL.getEditor (/Users/robjac/.atom/packages/tidal/lib/repl.coffee:67:19)
REPL.editorIsTidal (/Users/robjac/.atom/packages/tidal/lib/repl.coffee:29:13)
atom-workspace.REPL.atom.commands.add.tidal:boot (/Users/robjac/.atom/packages/tidal/lib/repl.coffee:22:23)
```

**Comment by robjac** [comment]
I'll try to help anyway I can //

**Comment by seansay** [comment]
@robjac 
I opened a issue the other day #14 
I'll take a look tomorrow, if you want you can send me a pull request, shoule be easy! Thanks

**Comment by robjac** [comment]
@seansay Oh sorry about duplicating the issue.

I'll send you a pull request if/when I have some free time! Thanks sean.

**Comment by seansay** [comment]
@robjac 
I remove all the old apis, not the warning shoule be gone after update to the new version

**Comment by robjac** [comment]
@seansay Excellent! great work dude! ; Installing now... 

cheers,
-Rob
