### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [seansay/atom-tidal#18]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.6.6`) of this package:

1. Call ::getActiveTextEditor instead
1. Use Decoration::setProperties instead
1. Use `editor.getCursorScreenPosition().row` instead
1. Use TextEditor::lineTextForBufferRow(bufferRow) instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by seansay** [comment]
working on this right now ! thanks

**Comment by seansay** [comment]
@benogle 
hey I just replace all the old api, and publish a new version
