### ISSUE TITLE
Not in scope: 'd1'

### ISSUE THREAD

**Issue by dpren** [seansay/atom-tidal#24]
I have Jack and Dirt running, but none of the Tidal functions are in scope. I can eval regular ghci stuff just fine from Atom, and Tidal is working for me outside of Atom.

**Comment by seansay** [comment]
can you give me a screenshot of the small prompt window after boot `ghci` in atom?

**Comment by dpren** [comment]
Hey Sean, here you go:

![Imgur](https://i.imgur.com/4Ps7mDG.png)

**Comment by seansay** [comment]
see `Could not find module 'Sound.Tidal.Context' `, seems that ghci cant find you tidal module? Could you install it again and try?

@yaxu do you know why this happens Alex?

**Comment by dpren** [comment]
I thought I'd done this, but I reinstalled anyways and it works now. Classic. Thanks!

**Comment by seansay** [comment]
@dpren good!!
