### ISSUE TITLE
Missing GHCI path setting

### ISSUE THREAD

**Issue by roguelj** [seansay/atom-tidal#26]
According to the readme:

3) The default ghci path is in /usr/local/bin/ghci, you can change this in the package setting view.

However, this setting is nowhere to be found in the Atom/Tidal package settings screen.

![image](https://cloud.githubusercontent.com/assets/6681635/12337429/fe54db28-bb01-11e5-8205-b86b5c9701a2.png)

![image](https://cloud.githubusercontent.com/assets/6681635/12337465/2ee2159e-bb02-11e5-8ee3-56625bff0cd0.png)

![image](https://cloud.githubusercontent.com/assets/6681635/12337456/21a54ca2-bb02-11e5-8208-b9a84650cef7.png)

Using 64 bit Atom 1.4.0 on Windows 10 with Tidal package 2.1.0

**Comment by roguelj** [comment]
My bad! Same as : https://github.com/seansay/atom-tidal/issues/6

**Comment by seansay** [comment]
:clap:
