### ISSUE TITLE
Move to tidalcycles?

### ISSUE THREAD

**Issue by yaxu** [seansay/atom-tidal#27]
Would it be possible to move this package to http://github.com/tidalcycles/atom-tidal/ so we can work on it collaboratively? I've forked it there + can add you as a collaborator.

**Comment by seansay** [comment]
Hi Alex, that's totally right way to go. Cheers

I've change the repo description so that people know the one in tidalcycles!

**Comment by yaxu** [comment]
Hey Sean,
Thanks for this, is it possible to point this at the tidalcycles repo? https://atom.io/packages/tidal

**Comment by seansay** [comment]
@yaxu,
I think thats possible, I'll look into this tonight

**Comment by yaxu** [comment]
Thanks !

**Comment by yaxu** [comment]
Hey @seansay, have been thinking it might be better + easier to make a new package TidalCycles for this that points to the new repository. This is partly so we can change the versioning to be in line with tidal, e.g. 0.8 for the upcoming version..

**Comment by seansay** [comment]
@yaxu 
thats more easier in the future , so you will create the new atom package right?

**Comment by aknuds1** [comment]
Hm... can [tidalcycles/atom-tidalcycles](https://github.com/tidalcycles/atom-tidalcycles) be made official somehow rather than a fork? Problem is I can't report issues in that repo, only its parent (i.e. this one).

**Comment by seansay** [comment]
@aknuds1 

I think it just need to be switch the `issues` feature on at github setting page.  cc  @yaxu 

<img width="700" alt="screen shot 2016-08-29 at 10 17 33 am" src="https://cloud.githubusercontent.com/assets/349342/18039076/de85e67e-6dd1-11e6-8f46-8ca0bd3bbf43.png">

**Comment by yaxu** [comment]
Just turned on the issues now, sorry for the delay. @seansay can you delete this version of the package?

**Comment by yaxu** [comment]
Ah, it seems the package must be unpublished before the github repository is deleted

**Comment by yaxu** [comment]
@seansay you just need to run `apm unpublish tidal`

**Comment by seansay** [comment]
Just did that
