### ISSUE TITLE
How to view Tidal warnings?

### ISSUE THREAD

**Issue by yaxu** [seansay/atom-tidal#3]
As I mentioned on issue #2, there doesn't seem to be a way to see tidal's error output. I managed to get a console up showing haskell output on the previous version, but can't find a way to do that now.

**Comment by seansay** [comment]
@yaxu 
yes, once we can got the haskell output, showing on the editor gui is not hard I think. I'll look at this weekend.

**Comment by yaxu** [comment]
Hey @seansay any progress with this? No hassle but I'm packaging a tidal live usb stick soon and wondering whether to have atom or emacs as default.. Atom could be a lot friendlier! :)

**Comment by yaxu** [comment]
Ok I found that you can get the console up with ctrl-shift-i
I also made this change to repl.coffee (my first coffeescript!):
```
  doSpawn: ->
    logStream = fs.createWriteStream('/tmp/tidal.err', {flags: 'a'});
    @repl = spawn(execPath, ['-XOverloadedStrings'])
    @repl.stdout.on('data', (data) -> console.log(data.toString('utf8')))
    @repl.stderr.pipe(logStream); 
```

i.e. to send the errors to an external file. Then the errors can be shown with some other program.

I don't know what's best here, maybe it could be an option.
Thanks again for all your work on this!

**Comment by seansay** [comment]
@yaxu 

I just publish `0.6.0`, and a small window bottom of the text-editor, put the console output to that.

**Comment by yaxu** [comment]
Hey

I just tried this, promising but when I click 'boot tidal' the whole window fills with output and I can't do much else..

![Uploading Screenshot from 2015-02-25 14:54:44.png . . .]()

**Comment by seansay** [comment]
@yaxu 
weird, I give it a height it shouble be like this .
![screen shot 2015-02-25 at 11 07 52 pm](https://cloud.githubusercontent.com/assets/349342/6373045/357dd28e-bd43-11e4-8e79-a2f849855160.png)

so you're on linux? which atom version

**Comment by yaxu** [comment]
Yes linux,

atom 0.176.0 26/01/2015 21:59:35

**Comment by seansay** [comment]
@yaxu 
just change a css selector, can u try that again?  Maybe I shoude get a linux to test..

**Comment by yaxu** [comment]
I'm just trying to upgrade atom to try it.. Although now atom isn't working at all, I think due to me using an old nodejs.. So upgrading htat.

**Comment by yaxu** [comment]
Ok I upgraded to latest atom and all is fine now. I don't know if it is due to my editor version or the css selector but it works! Thanks very much @seansay
