### ISSUE TITLE
Location of ghci

### ISSUE THREAD

**Issue by yaxu** [seansay/atom-tidal#5]
The location is set to `/usr/local/bin/ghci` but in a lot of systems it will be `/usr/bin/ghci`. Maybe the plugin could try both? It could also be an option.

Thanks!

**Comment by kindohm** [comment]
This is also an issue for Windows installs. It would be great if this option could be configurable.

**Comment by seansay** [comment]
@yaxu @kindohm 
thx you guys! just make it configurable in the atom package setting!

**Comment by kindohm** [comment]
what is the proper way to fork, install, and test this change? it isn't clear to me from the Atom docs how to do this. I don't see a way to install my fork'ed package in Atom without it being published to Atom's package repository.

**Comment by yaxu** [comment]
Thanks !

**Comment by kindohm** [comment]
updated the package, and I still don't see this config setting. I uninstalled the package, closed Atom, installed it again (version 0.6.1), verified the code is correct locally, and I still don't see the setting. I would expect to see it above the Keybindings section:

![](http://i.imgur.com/NcEGld3.png)

**Comment by seansay** [comment]
@kindohm 
good! sure  the `apm` and `atom -d`  it's not easy to find in the atom doc
