### ISSUE TITLE
ghci config path still not visible

### ISSUE THREAD

**Issue by kindohm** [seansay/atom-tidal#6]
After upgrading to 0.6.1, the ghci path still does not show up in the Tidal package settings. This is on Windows 8.1, Atom 0.182.0,  I see no issue with the package code as-is, so I don't know what the problem is. I'm able to add/modify settings in other packages without issue. Curious if anyone besides me cannot see the ghci setting either.

![image](https://cloud.githubusercontent.com/assets/9797/6374901/70f3525e-bcd9-11e4-95ff-842f6dcf0aa1.png)

**Comment by seansay** [comment]
not sure it's an windows only problem? I don't have a window machine around :( Can you reproduce on other window machine?

**Comment by kindohm** [comment]
If you boot Tidal in Atom first, then the config settings will show. The package has to be "activated" first before the settings show up. This is a known bug in Atom, see https://discuss.atom.io/t/configuration-vars-dont-show-up/14480 and https://github.com/atom/settings-view/issues/356.
