### ISSUE TITLE
'cmd-enter' keybinding does not work on Windows or Linux

### ISSUE THREAD

**Issue by kindohm** [seansay/atom-tidal#7]
The `cmd-enter` keybinding to evaluate multiple lines does not work on Windows or Linux because there is no `cmd` key.  

An additional `ctrl-enter` keybinding should work. Any concerns about adding this? I have a fix ready to go.

**Comment by seansay** [comment]
look good to me, not sure atom has os specfic keybinding setting, but have both key should be fine on mac 

@yaxu

**Comment by yaxu** [comment]
I think the emacs plugin uses alt-enter, it might be nice to standardise.

**Comment by yaxu** [comment]
I tell a lie, it's ctrl-enter in emacs as well!

**Comment by seansay** [comment]
@yaxu @kindohm 
let's add a ctrl-enter binding!

**Comment by kindohm** [comment]
I'll send the PR soon

**Comment by kindohm** [comment]
submitted a pull request: https://github.com/seansay/atom-tidal/pull/8
